/**
 * 🌍 PAÍSES (PJODC v4)
 *
 * Lista estática: carrega junto com o bundle, sem depender de rede.
 *
 * Motivo (2026-08-31): a API restcountries.com/v3.1 foi descontinuada e passou a
 * responder um objeto de erro no lugar do array. O `data.sort()` do formulário
 * lançava TypeError, caía no catch, e o campo País ficava permanentemente vazio.
 * A v5 devolve a mesma descontinuação — não havia URL para trocar.
 *
 * As cidades continuam vindo do IBGE, que responde normalmente: são 5.570
 * municípios (~1 MB), grandes demais para embutir no bundle.
 */

/** Opção de um campo de seleção geográfica. */
export interface LocationOption {
  /** Texto exibido ao usuário (com bandeira, quando houver). */
  label: string;
  /** Valor gravado no banco. */
  value: string;
}

/** Padrão do formulário de cadastro (users.country é NOT NULL DEFAULT 'BRASIL'). */
export const DEFAULT_COUNTRY = 'BRASIL';

/** 248 países em português, ordenados por nome. */
export const COUNTRIES: LocationOption[] = [
  { label: '🇦🇫 AFEGANISTÃO', value: 'AFEGANISTÃO' },
  { label: '🇿🇦 ÁFRICA DO SUL', value: 'ÁFRICA DO SUL' },
  { label: '🇦🇱 ALBÂNIA', value: 'ALBÂNIA' },
  { label: '🇩🇪 ALEMANHA', value: 'ALEMANHA' },
  { label: '🇦🇩 ANDORRA', value: 'ANDORRA' },
  { label: '🇦🇴 ANGOLA', value: 'ANGOLA' },
  { label: '🇦🇮 ANGUILA', value: 'ANGUILA' },
  { label: '🇦🇶 ANTÁRTIDA', value: 'ANTÁRTIDA' },
  { label: '🇦🇬 ANTÍGUA E BARBUDA', value: 'ANTÍGUA E BARBUDA' },
  { label: '🇸🇦 ARÁBIA SAUDITA', value: 'ARÁBIA SAUDITA' },
  { label: '🇩🇿 ARGÉLIA', value: 'ARGÉLIA' },
  { label: '🇦🇷 ARGENTINA', value: 'ARGENTINA' },
  { label: '🇦🇲 ARMÊNIA', value: 'ARMÊNIA' },
  { label: '🇦🇼 ARUBA', value: 'ARUBA' },
  { label: '🇦🇺 AUSTRÁLIA', value: 'AUSTRÁLIA' },
  { label: '🇦🇹 ÁUSTRIA', value: 'ÁUSTRIA' },
  { label: '🇦🇿 AZERBAIJÃO', value: 'AZERBAIJÃO' },
  { label: '🇧🇸 BAHAMAS', value: 'BAHAMAS' },
  { label: '🇧🇩 BANGLADESH', value: 'BANGLADESH' },
  { label: '🇧🇧 BARBADOS', value: 'BARBADOS' },
  { label: '🇧🇭 BAREIN', value: 'BAREIN' },
  { label: '🇧🇪 BÉLGICA', value: 'BÉLGICA' },
  { label: '🇧🇿 BELIZE', value: 'BELIZE' },
  { label: '🇧🇯 BENIN', value: 'BENIN' },
  { label: '🇧🇲 BERMUDAS', value: 'BERMUDAS' },
  { label: '🇧🇾 BIELORRÚSSIA', value: 'BIELORRÚSSIA' },
  { label: '🇧🇴 BOLÍVIA', value: 'BOLÍVIA' },
  { label: '🇧🇦 BÓSNIA E HERZEGOVINA', value: 'BÓSNIA E HERZEGOVINA' },
  { label: '🇧🇼 BOTSUANA', value: 'BOTSUANA' },
  { label: '🇧🇷 BRASIL', value: 'BRASIL' },
  { label: '🇧🇳 BRUNEI', value: 'BRUNEI' },
  { label: '🇧🇬 BULGÁRIA', value: 'BULGÁRIA' },
  { label: '🇧🇫 BURQUINA FASO', value: 'BURQUINA FASO' },
  { label: '🇧🇮 BURUNDI', value: 'BURUNDI' },
  { label: '🇧🇹 BUTÃO', value: 'BUTÃO' },
  { label: '🇨🇻 CABO VERDE', value: 'CABO VERDE' },
  { label: '🇨🇲 CAMARÕES', value: 'CAMARÕES' },
  { label: '🇰🇭 CAMBOJA', value: 'CAMBOJA' },
  { label: '🇨🇦 CANADÁ', value: 'CANADÁ' },
  { label: '🇶🇦 CATAR', value: 'CATAR' },
  { label: '🇰🇿 CAZAQUISTÃO', value: 'CAZAQUISTÃO' },
  { label: '🇹🇩 CHADE', value: 'CHADE' },
  { label: '🇨🇱 CHILE', value: 'CHILE' },
  { label: '🇨🇳 CHINA', value: 'CHINA' },
  { label: '🇨🇾 CHIPRE', value: 'CHIPRE' },
  { label: '🇻🇦 CIDADE DO VATICANO', value: 'CIDADE DO VATICANO' },
  { label: '🇨🇴 COLÔMBIA', value: 'COLÔMBIA' },
  { label: '🇰🇲 COMORES', value: 'COMORES' },
  { label: '🇨🇩 CONGO - KINSHASA', value: 'CONGO - KINSHASA' },
  { label: '🇰🇵 COREIA DO NORTE', value: 'COREIA DO NORTE' },
  { label: '🇰🇷 COREIA DO SUL', value: 'COREIA DO SUL' },
  { label: '🇨🇮 COSTA DO MARFIM', value: 'COSTA DO MARFIM' },
  { label: '🇨🇷 COSTA RICA', value: 'COSTA RICA' },
  { label: '🇭🇷 CROÁCIA', value: 'CROÁCIA' },
  { label: '🇨🇺 CUBA', value: 'CUBA' },
  { label: '🇨🇼 CURAÇAO', value: 'CURAÇAO' },
  { label: '🇩🇰 DINAMARCA', value: 'DINAMARCA' },
  { label: '🇩🇯 DJIBUTI', value: 'DJIBUTI' },
  { label: '🇩🇲 DOMINICA', value: 'DOMINICA' },
  { label: '🇪🇬 EGITO', value: 'EGITO' },
  { label: '🇸🇻 EL SALVADOR', value: 'EL SALVADOR' },
  { label: '🇦🇪 EMIRADOS ÁRABES UNIDOS', value: 'EMIRADOS ÁRABES UNIDOS' },
  { label: '🇪🇨 EQUADOR', value: 'EQUADOR' },
  { label: '🇪🇷 ERITREIA', value: 'ERITREIA' },
  { label: '🇸🇰 ESLOVÁQUIA', value: 'ESLOVÁQUIA' },
  { label: '🇸🇮 ESLOVÊNIA', value: 'ESLOVÊNIA' },
  { label: '🇪🇸 ESPANHA', value: 'ESPANHA' },
  { label: '🇸🇿 ESSUATÍNI', value: 'ESSUATÍNI' },
  { label: '🇺🇸 ESTADOS UNIDOS', value: 'ESTADOS UNIDOS' },
  { label: '🇪🇪 ESTÔNIA', value: 'ESTÔNIA' },
  { label: '🇪🇹 ETIÓPIA', value: 'ETIÓPIA' },
  { label: '🇫🇯 FIJI', value: 'FIJI' },
  { label: '🇵🇭 FILIPINAS', value: 'FILIPINAS' },
  { label: '🇫🇮 FINLÂNDIA', value: 'FINLÂNDIA' },
  { label: '🇫🇷 FRANÇA', value: 'FRANÇA' },
  { label: '🇬🇦 GABÃO', value: 'GABÃO' },
  { label: '🇬🇲 GÂMBIA', value: 'GÂMBIA' },
  { label: '🇬🇭 GANA', value: 'GANA' },
  { label: '🇬🇪 GEÓRGIA', value: 'GEÓRGIA' },
  { label: '🇬🇮 GIBRALTAR', value: 'GIBRALTAR' },
  { label: '🇬🇩 GRANADA', value: 'GRANADA' },
  { label: '🇬🇷 GRÉCIA', value: 'GRÉCIA' },
  { label: '🇬🇱 GROENLÂNDIA', value: 'GROENLÂNDIA' },
  { label: '🇬🇵 GUADALUPE', value: 'GUADALUPE' },
  { label: '🇬🇺 GUAM', value: 'GUAM' },
  { label: '🇬🇹 GUATEMALA', value: 'GUATEMALA' },
  { label: '🇬🇬 GUERNSEY', value: 'GUERNSEY' },
  { label: '🇬🇾 GUIANA', value: 'GUIANA' },
  { label: '🇬🇫 GUIANA FRANCESA', value: 'GUIANA FRANCESA' },
  { label: '🇬🇳 GUINÉ', value: 'GUINÉ' },
  { label: '🇬🇶 GUINÉ EQUATORIAL', value: 'GUINÉ EQUATORIAL' },
  { label: '🇬🇼 GUINÉ-BISSAU', value: 'GUINÉ-BISSAU' },
  { label: '🇭🇹 HAITI', value: 'HAITI' },
  { label: '🇭🇳 HONDURAS', value: 'HONDURAS' },
  { label: '🇭🇰 HONG KONG, RAE DA CHINA', value: 'HONG KONG, RAE DA CHINA' },
  { label: '🇭🇺 HUNGRIA', value: 'HUNGRIA' },
  { label: '🇾🇪 IÊMEN', value: 'IÊMEN' },
  { label: '🇧🇻 ILHA BOUVET', value: 'ILHA BOUVET' },
  { label: '🇨🇽 ILHA CHRISTMAS', value: 'ILHA CHRISTMAS' },
  { label: '🇮🇲 ILHA DE MAN', value: 'ILHA DE MAN' },
  { label: '🇳🇫 ILHA NORFOLK', value: 'ILHA NORFOLK' },
  { label: '🇦🇽 ILHAS ALAND', value: 'ILHAS ALAND' },
  { label: '🇰🇾 ILHAS CAYMAN', value: 'ILHAS CAYMAN' },
  { label: '🇨🇨 ILHAS COCOS (KEELING)', value: 'ILHAS COCOS (KEELING)' },
  { label: '🇨🇰 ILHAS COOK', value: 'ILHAS COOK' },
  { label: '🇫🇴 ILHAS FAROÉ', value: 'ILHAS FAROÉ' },
  { label: '🇬🇸 ILHAS GEÓRGIA DO SUL E SANDWICH DO SUL', value: 'ILHAS GEÓRGIA DO SUL E SANDWICH DO SUL' },
  { label: '🇭🇲 ILHAS HEARD E MCDONALD', value: 'ILHAS HEARD E MCDONALD' },
  { label: '🇫🇰 ILHAS MALVINAS', value: 'ILHAS MALVINAS' },
  { label: '🇲🇵 ILHAS MARIANAS DO NORTE', value: 'ILHAS MARIANAS DO NORTE' },
  { label: '🇲🇭 ILHAS MARSHALL', value: 'ILHAS MARSHALL' },
  { label: '🇺🇲 ILHAS MENORES DISTANTES DOS EUA', value: 'ILHAS MENORES DISTANTES DOS EUA' },
  { label: '🇵🇳 ILHAS PITCAIRN', value: 'ILHAS PITCAIRN' },
  { label: '🇸🇧 ILHAS SALOMÃO', value: 'ILHAS SALOMÃO' },
  { label: '🇹🇨 ILHAS TURCAS E CAICOS', value: 'ILHAS TURCAS E CAICOS' },
  { label: '🇻🇮 ILHAS VIRGENS AMERICANAS', value: 'ILHAS VIRGENS AMERICANAS' },
  { label: '🇻🇬 ILHAS VIRGENS BRITÂNICAS', value: 'ILHAS VIRGENS BRITÂNICAS' },
  { label: '🇮🇳 ÍNDIA', value: 'ÍNDIA' },
  { label: '🇮🇩 INDONÉSIA', value: 'INDONÉSIA' },
  { label: '🇮🇷 IRÃ', value: 'IRÃ' },
  { label: '🇮🇶 IRAQUE', value: 'IRAQUE' },
  { label: '🇮🇪 IRLANDA', value: 'IRLANDA' },
  { label: '🇮🇸 ISLÂNDIA', value: 'ISLÂNDIA' },
  { label: '🇮🇱 ISRAEL', value: 'ISRAEL' },
  { label: '🇮🇹 ITÁLIA', value: 'ITÁLIA' },
  { label: '🇯🇲 JAMAICA', value: 'JAMAICA' },
  { label: '🇯🇵 JAPÃO', value: 'JAPÃO' },
  { label: '🇯🇪 JERSEY', value: 'JERSEY' },
  { label: '🇯🇴 JORDÂNIA', value: 'JORDÂNIA' },
  { label: '🇰🇼 KUWAIT', value: 'KUWAIT' },
  { label: '🇱🇦 LAOS', value: 'LAOS' },
  { label: '🇱🇸 LESOTO', value: 'LESOTO' },
  { label: '🇱🇻 LETÔNIA', value: 'LETÔNIA' },
  { label: '🇱🇧 LÍBANO', value: 'LÍBANO' },
  { label: '🇱🇷 LIBÉRIA', value: 'LIBÉRIA' },
  { label: '🇱🇾 LÍBIA', value: 'LÍBIA' },
  { label: '🇱🇮 LIECHTENSTEIN', value: 'LIECHTENSTEIN' },
  { label: '🇱🇹 LITUÂNIA', value: 'LITUÂNIA' },
  { label: '🇱🇺 LUXEMBURGO', value: 'LUXEMBURGO' },
  { label: '🇲🇴 MACAU, RAE DA CHINA', value: 'MACAU, RAE DA CHINA' },
  { label: '🇲🇰 MACEDÔNIA DO NORTE', value: 'MACEDÔNIA DO NORTE' },
  { label: '🇲🇬 MADAGASCAR', value: 'MADAGASCAR' },
  { label: '🇲🇾 MALÁSIA', value: 'MALÁSIA' },
  { label: '🇲🇼 MALAUI', value: 'MALAUI' },
  { label: '🇲🇻 MALDIVAS', value: 'MALDIVAS' },
  { label: '🇲🇱 MALI', value: 'MALI' },
  { label: '🇲🇹 MALTA', value: 'MALTA' },
  { label: '🇲🇦 MARROCOS', value: 'MARROCOS' },
  { label: '🇲🇶 MARTINICA', value: 'MARTINICA' },
  { label: '🇲🇺 MAURÍCIO', value: 'MAURÍCIO' },
  { label: '🇲🇷 MAURITÂNIA', value: 'MAURITÂNIA' },
  { label: '🇾🇹 MAYOTTE', value: 'MAYOTTE' },
  { label: '🇲🇽 MÉXICO', value: 'MÉXICO' },
  { label: '🇲🇲 MIANMAR (BIRMÂNIA)', value: 'MIANMAR (BIRMÂNIA)' },
  { label: '🇫🇲 MICRONÉSIA', value: 'MICRONÉSIA' },
  { label: '🇲🇿 MOÇAMBIQUE', value: 'MOÇAMBIQUE' },
  { label: '🇲🇩 MOLDÁVIA', value: 'MOLDÁVIA' },
  { label: '🇲🇨 MÔNACO', value: 'MÔNACO' },
  { label: '🇲🇳 MONGÓLIA', value: 'MONGÓLIA' },
  { label: '🇲🇪 MONTENEGRO', value: 'MONTENEGRO' },
  { label: '🇲🇸 MONTSERRAT', value: 'MONTSERRAT' },
  { label: '🇳🇦 NAMÍBIA', value: 'NAMÍBIA' },
  { label: '🇳🇷 NAURU', value: 'NAURU' },
  { label: '🇳🇵 NEPAL', value: 'NEPAL' },
  { label: '🇳🇮 NICARÁGUA', value: 'NICARÁGUA' },
  { label: '🇳🇪 NÍGER', value: 'NÍGER' },
  { label: '🇳🇬 NIGÉRIA', value: 'NIGÉRIA' },
  { label: '🇳🇺 NIUE', value: 'NIUE' },
  { label: '🇳🇴 NORUEGA', value: 'NORUEGA' },
  { label: '🇳🇨 NOVA CALEDÔNIA', value: 'NOVA CALEDÔNIA' },
  { label: '🇳🇿 NOVA ZELÂNDIA', value: 'NOVA ZELÂNDIA' },
  { label: '🇴🇲 OMÃ', value: 'OMÃ' },
  { label: '🇳🇱 PAÍSES BAIXOS', value: 'PAÍSES BAIXOS' },
  { label: '🇵🇼 PALAU', value: 'PALAU' },
  { label: '🇵🇦 PANAMÁ', value: 'PANAMÁ' },
  { label: '🇵🇬 PAPUA-NOVA GUINÉ', value: 'PAPUA-NOVA GUINÉ' },
  { label: '🇵🇰 PAQUISTÃO', value: 'PAQUISTÃO' },
  { label: '🇵🇾 PARAGUAI', value: 'PARAGUAI' },
  { label: '🇵🇪 PERU', value: 'PERU' },
  { label: '🇵🇫 POLINÉSIA FRANCESA', value: 'POLINÉSIA FRANCESA' },
  { label: '🇵🇱 POLÔNIA', value: 'POLÔNIA' },
  { label: '🇵🇷 PORTO RICO', value: 'PORTO RICO' },
  { label: '🇵🇹 PORTUGAL', value: 'PORTUGAL' },
  { label: '🇰🇪 QUÊNIA', value: 'QUÊNIA' },
  { label: '🇰🇬 QUIRGUISTÃO', value: 'QUIRGUISTÃO' },
  { label: '🇰🇮 QUIRIBATI', value: 'QUIRIBATI' },
  { label: '🇬🇧 REINO UNIDO', value: 'REINO UNIDO' },
  { label: '🇨🇫 REPÚBLICA CENTRO-AFRICANA', value: 'REPÚBLICA CENTRO-AFRICANA' },
  { label: '🇨🇬 REPÚBLICA DO CONGO', value: 'REPÚBLICA DO CONGO' },
  { label: '🇩🇴 REPÚBLICA DOMINICANA', value: 'REPÚBLICA DOMINICANA' },
  { label: '🇷🇪 REUNIÃO', value: 'REUNIÃO' },
  { label: '🇷🇴 ROMÊNIA', value: 'ROMÊNIA' },
  { label: '🇷🇼 RUANDA', value: 'RUANDA' },
  { label: '🇷🇺 RÚSSIA', value: 'RÚSSIA' },
  { label: '🇪🇭 SAARA OCIDENTAL', value: 'SAARA OCIDENTAL' },
  { label: '🇼🇸 SAMOA', value: 'SAMOA' },
  { label: '🇦🇸 SAMOA AMERICANA', value: 'SAMOA AMERICANA' },
  { label: '🇸🇲 SAN MARINO', value: 'SAN MARINO' },
  { label: '🇸🇭 SANTA HELENA', value: 'SANTA HELENA' },
  { label: '🇱🇨 SANTA LÚCIA', value: 'SANTA LÚCIA' },
  { label: '🇧🇱 SÃO BARTOLOMEU', value: 'SÃO BARTOLOMEU' },
  { label: '🇰🇳 SÃO CRISTÓVÃO E NÉVIS', value: 'SÃO CRISTÓVÃO E NÉVIS' },
  { label: '🇲🇫 SÃO MARTINHO', value: 'SÃO MARTINHO' },
  { label: '🇵🇲 SÃO PEDRO E MIQUELÃO', value: 'SÃO PEDRO E MIQUELÃO' },
  { label: '🇸🇹 SÃO TOMÉ E PRÍNCIPE', value: 'SÃO TOMÉ E PRÍNCIPE' },
  { label: '🇻🇨 SÃO VICENTE E GRANADINAS', value: 'SÃO VICENTE E GRANADINAS' },
  { label: '🇸🇨 SEICHELES', value: 'SEICHELES' },
  { label: '🇸🇳 SENEGAL', value: 'SENEGAL' },
  { label: '🇸🇱 SERRA LEOA', value: 'SERRA LEOA' },
  { label: '🇷🇸 SÉRVIA', value: 'SÉRVIA' },
  { label: '🇸🇬 SINGAPURA', value: 'SINGAPURA' },
  { label: '🇸🇽 SINT MAARTEN', value: 'SINT MAARTEN' },
  { label: '🇸🇾 SÍRIA', value: 'SÍRIA' },
  { label: '🇸🇴 SOMÁLIA', value: 'SOMÁLIA' },
  { label: '🇱🇰 SRI LANKA', value: 'SRI LANKA' },
  { label: '🇸🇩 SUDÃO', value: 'SUDÃO' },
  { label: '🇸🇸 SUDÃO DO SUL', value: 'SUDÃO DO SUL' },
  { label: '🇸🇪 SUÉCIA', value: 'SUÉCIA' },
  { label: '🇨🇭 SUÍÇA', value: 'SUÍÇA' },
  { label: '🇸🇷 SURINAME', value: 'SURINAME' },
  { label: '🇸🇯 SVALBARD E JAN MAYEN', value: 'SVALBARD E JAN MAYEN' },
  { label: '🇹🇯 TADJIQUISTÃO', value: 'TADJIQUISTÃO' },
  { label: '🇹🇭 TAILÂNDIA', value: 'TAILÂNDIA' },
  { label: '🇹🇼 TAIWAN', value: 'TAIWAN' },
  { label: '🇹🇿 TANZÂNIA', value: 'TANZÂNIA' },
  { label: '🇨🇿 TCHÉQUIA', value: 'TCHÉQUIA' },
  { label: '🇮🇴 TERRITÓRIO BRITÂNICO DO OCEANO ÍNDICO', value: 'TERRITÓRIO BRITÂNICO DO OCEANO ÍNDICO' },
  { label: '🇹🇫 TERRITÓRIOS FRANCESES DO SUL', value: 'TERRITÓRIOS FRANCESES DO SUL' },
  { label: '🇵🇸 TERRITÓRIOS PALESTINOS', value: 'TERRITÓRIOS PALESTINOS' },
  { label: '🇹🇱 TIMOR-LESTE', value: 'TIMOR-LESTE' },
  { label: '🇹🇬 TOGO', value: 'TOGO' },
  { label: '🇹🇰 TOKELAU', value: 'TOKELAU' },
  { label: '🇹🇴 TONGA', value: 'TONGA' },
  { label: '🇹🇹 TRINIDAD E TOBAGO', value: 'TRINIDAD E TOBAGO' },
  { label: '🇹🇳 TUNÍSIA', value: 'TUNÍSIA' },
  { label: '🇹🇲 TURCOMENISTÃO', value: 'TURCOMENISTÃO' },
  { label: '🇹🇷 TURQUIA', value: 'TURQUIA' },
  { label: '🇹🇻 TUVALU', value: 'TUVALU' },
  { label: '🇺🇦 UCRÂNIA', value: 'UCRÂNIA' },
  { label: '🇺🇬 UGANDA', value: 'UGANDA' },
  { label: '🇺🇾 URUGUAI', value: 'URUGUAI' },
  { label: '🇺🇿 UZBEQUISTÃO', value: 'UZBEQUISTÃO' },
  { label: '🇻🇺 VANUATU', value: 'VANUATU' },
  { label: '🇻🇪 VENEZUELA', value: 'VENEZUELA' },
  { label: '🇻🇳 VIETNÃ', value: 'VIETNÃ' },
  { label: '🇼🇫 WALLIS E FUTUNA', value: 'WALLIS E FUTUNA' },
  { label: '🇿🇲 ZÂMBIA', value: 'ZÂMBIA' },
  { label: '🇿🇼 ZIMBÁBUE', value: 'ZIMBÁBUE' },
];
